-- CREATE TABLE STUDENT(
-- STUDENTID CHAR(4),
-- STUDENTNAME VARCHAR(25),
-- STUDENTDOB DATE,
-- STUDENTGPA DECIMAL(4,2),
-- STUDENTSUBURB VARCHAR(20),
-- PRIMARY KEY (STUDENTID));

CREATE TABLE UNIT(
UNITCODE CHAR(4),
UNITNAME VARCHAR(30),
UNITDESCRIPTION VARCHAR(50),
UNITCREDITPOINTS SMALLINT,
PRIMARY KEY (UNITCODE));

CREATE TABLE TEACHER(
TEACHERID CHAR(4),
TEACHERNAME VARCHAR(25),
TEACHERDESIGNATION VARCHAR(20),
TEACHERSALARY INTEGER,
PRIMARY KEY (TEACHERID));

CREATE TABLE ENROLMENT(
ENROLMENTID CHAR(4),
SEMESTER VARCHAR(10),
STUDYYEAR SMALLINT,
STUDENTID CHAR(4),
UNITCODE CHAR(6),
PRIMARY KEY (ENROLMENTID),
FOREIGN KEY (STUDENTID) REFERENCES STUDENT(STUDENTID),
FOREIGN KEY (UNITCODE) REFERENCES UNIT(UNITCODE));

CREATE TABLE WORKLOAD(
TEACHERID CHAR(4),
UNITCODE CHAR(6),
SCHEDULEHOURS DECIMAL(4,2),
PAYRATE NUMERIC(4,2),
PRIMARY KEY (TEACHERID, UNITCODE),
FOREIGN KEY (TEACHERID) REFERENCES TEACHER(TEACHERID),
FOREIGN KEY (UNITCODE) REFERENCES UNIT(UNITCODE));

SHOW TABLES;

INSERT INTO STUDENT VALUES ("S001","MICHAEL BEVAN","1960-09-15","3.2","CHATSWOOD");
INSERT INTO STUDENT VALUES ("S002","BRIAN LARA","1965-02-10","4.0","MARSFIELD");
INSERT INTO STUDENT VALUES ("S003","VIVAN RICHARDS","1958-11-12","4.5","BURWOOD");
INSERT INTO STUDENT VALUES ("S004","JAVED MIANDAD","1966-05-05","3.5","RYDE");
INSERT INTO STUDENT VALUES ("S005","VIRAT KOHLI","1988-10-15","4.3","AUBURN");
INSERT INTO STUDENT VALUES ("S006","BABAR AZAM","1991-04-20","4.2","LAKEMBA");
INSERT INTO STUDENT VALUES ("S007","KUMAR SANGAKARA","1980-01-26","3.7","REDFERN");

SELECT * FROM STUDENT;

SHOW CREATE TABLE enrolment;
ALTER TABLE ENROLMENT
DROP FOREIGN KEY enrolment_ibfk_2;

ALTER TABLE WORKLOAD
DROP FOREIGN KEY workload_ibfk_1;

ALTER TABLE WORKLOAD
DROP FOREIGN KEY workload_ibfk_2;

ALTER TABLE UNIT
MODIFY COLUMN UNITCODE CHAR(6);

ALTER TABLE enrolment
ADD CONSTRAINT enrolment_ibfk_2 FOREIGN KEY (UNITCODE) REFERENCES UNIT(UNITCODE);

ALTER TABLE WORKLOAD
ADD CONSTRAINT workload_ibfk_1 FOREIGN KEY (UNITCODE) REFERENCES UNIT(UNITCODE);

ALTER TABLE WORKLOAD
ADD CONSTRAINT workload_ibfk_2 FOREIGN KEY (UNITCODE) REFERENCES UNIT(UNITCODE);

INSERT INTO UNIT VALUES ("MDS600","PROGRAMMING","FUNDAMENTALS OF 
COMPUTER PROGRAMMING",3);
INSERT INTO UNIT VALUES ("MDS601","DATABASES","INTRODUCTION TO 
DATABASES",3);
INSERT INTO UNIT VALUES ("MDS602","MATHEMATICS","BASIC MATHS FOR DATA 
SCIENCE",2);
INSERT INTO UNIT VALUES ("MDS603","DATA SCIENCE","INTRODUCTION TO DATA 
SCIECNE METHODOLOGY",4);
INSERT INTO UNIT VALUES ("MDS604","MACHINE LEARNING","MACHINE LEARNING 
FOR DATA SCIENCE",3);
INSERT INTO UNIT VALUES ("MDS605","BUSSINES ANALYTICS","BASICS OF 
BUSSINES ANALYTICS",2);
INSERT INTO UNIT VALUES ("MDS606","ADAVANCED DATABASES","ADVACNE TOPICS 
IN DATABASES",3);

INSERT INTO TEACHER VALUES ("T001", "WASIM AKRAM", "ASSOCIATE PROFESSOR", "200000");
INSERT INTO TEACHER VALUES ("T002", "WASIM AKRAM", "ASSOCIATE PROFESSOR", "200000");

